export const FETCH_TOP_ARTISTS_START = 'FETCH_TOP_ARTISTS_START';
export const FETCH_TOP_ARTISTS_SUCCESS = 'FETCH_TOP_ARTISTS_SUCCESS';
export const FETCH_TOP_ARTISTS_FAIL = 'FETCH_TOP_ARTISTS_FAIL';

export const FETCH_TOP_TRACKS_START = 'FETCH_TOP_TRACKS_START';
export const FETCH_TOP_TRACKS_SUCCESS = 'FETCH_TOP_TRACKS_SUCCESS';
export const FETCH_TOP_TRACKS_FAIL = 'FETCH_TOP_TRACKS_FAIL';

export const FETCH_SEARCH_ARTISTS_START = 'FETCH_SEARCH_ARTISTS_START';
export const FETCH_SEARCH_ARTISTS_SUCCESS = 'FETCH_SEARCH_ARTISTS_SUCCESS';
export const FETCH_SEARCH_ARTISTS_FAIL = 'FETCH_SEARCH_ARTISTS_FAIL';

export const FETCH_SEARCH_TRACKS_START = 'FETCH_SEARCH_TRACKS_START';
export const FETCH_SEARCH_TRACKS_SUCCESS = 'FETCH_SEARCH_TRACKS_SUCCESS';
export const FETCH_SEARCH_TRACKS_FAIL = 'FETCH_SEARCH_TRACKS_FAIL';
